remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: Возьмите подростка?
includes:
  - sidebar.html
defaults:
  - scope:
      path: ""
    values:
      image: /dogs/img/dogs-all.png
